### ISSUE TITLE
Implement Trippie UI class

### ISSUE THREAD

**Issue by ivanderjmw** [AY2021S1-CS2113T-W11-2/tp#16]
Create a Trippie UI class to handle user input and output.
User story: As a user, I want to have a simple UI so that I can directly use Trippie without learning beforehand.

**Comment by SameerKhurana** [comment]
Hi Ivander,

Can you please elaborate the requirement. I tried setting up project locally but I could not find the Duke.java in the repo,I can only see Trippie.java file with main method.

Thanks,
Sameer

**Comment by ivanderjmw** [comment]
Hello Sameer,

I opened a new issue for the mismatched project requirements. Our team will update it ASAP. Please check #19 

Regards,
Ivander
