### ISSUE TITLE
Some comments on your DG.

### ISSUE THREAD

**Issue by okkhoy** [AY2021S1-CS2113T-W11-2/tp#83]
- [x] in all the descriptions change "architecture diagram of XYZ class" -> "class diagram"

- [x]  Is the annotated item in the image below an arrow mark? if so, please fix it 
![image](https://user-images.githubusercontent.com/1023494/97514310-57f92a00-19c9-11eb-8860-205696a25032.png)

- [x] several (possibly minor) issues in the sequence diagram. see annotations.
![image](https://user-images.githubusercontent.com/1023494/97573936-72f98780-1a25-11eb-901c-cb7a9677c98a.png)

- [x] nitpicks below
![image](https://user-images.githubusercontent.com/1023494/97574457-3bd7a600-1a26-11eb-807a-29806ce6bfed.png)

- [x] figure 4: sequence diagram same issue with the object notation as above (fix it everywhere in the DG)

- [x] class diagram issues (probably a tool limitation, try to fix it)
![image](https://user-images.githubusercontent.com/1023494/97575030-14350d80-1a27-11eb-8635-94ee514bdf5e.png)

- [x] In the lines: `The Command class is designed as the parent class for other command classes (e.g. NewTripCommand, AddExpenseCommand, ExitCommand etc). Below shows the architecture diagram for the Command class`: 
change `architecture diagram for the Command class` -> `class diagram`

- [x] class diagram can be simplified if you wish:
![image](https://user-images.githubusercontent.com/1023494/97576812-99212680-1a29-11eb-876f-d3af511aa304.png)

- [x] potential problem with navigability
![image](https://user-images.githubusercontent.com/1023494/97577023-d38ac380-1a29-11eb-8d9d-3be8dd64db3d.png)

- [x] why does your instructions for manual testing have class diagrams? that section should have at minimum you command formats and a few cases of using the commands (like positive and negative ways). move the class diagrams up to the design/implementation section. Section 6.1 onwards seem fine (though you can make the commands more prominent).

- [x] **Simplify the class diagrams in section 6.0.**: They have too many methods, with little or no explanation. Makes it cumbersome to read and possibly to maintain later. So you can try to simplify them by retaining only key methods. Also there are some notation problems like the one below. Try to fix them.
![image](https://user-images.githubusercontent.com/1023494/97577658-aab6fe00-1a2a-11eb-85e4-410575c5da38.png)

**Comment by ivanderjmw** [comment]
@felixhalim fix the miro diagrams. I will fix the UMLs.

**Comment by ivanderjmw** [comment]
All checks done!
